[package]
name = "pdf_tools"
version = "0.1.0"
authors = ["Sebastian K <s3bk@protonmail.com>"]
edition = "2018"

[dependencies]
pdf = { git = "https://github.com/pdf-rs/pdf", features = [ "euclid" ] }
pdf_encoding = "0.3.0"
euclid = "0.22.6"
log = "*"
clap = {version = "3.1.7", features = ["derive"]}
